---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
    force: False
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
    privileged: true
    capabilities:
      - SYS_ADMIN
    exposed_ports:
      - 123/udp
      - 12000/udp
      - 13000/tcp
      - 30303/tcp
      - 9090/tcp
      - 3000/tcp
    published_ports:
      - 0.0.0.0:8123:123/udp
      - 0.0.0.0:12000:12000/udp
      - 0.0.0.0:13000:13000/tcp
      - 0.0.0.0:30303:30303/tcp
      - 0.0.0.0:9090:9090/tcp
      - 0.0.0.0:3000:3000/tcp
    command: /sbin/init
    security_opts:
      - seccomp=path/to/seccomp.json
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  inventory:
    host_vars:
      ansible_user: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
