{
 "title": "Slasher",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Batch processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(slasher_process_batch_time_sum[30s])\n/\nrate(slasher_process_batch_time_count[30s])"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "slasher_database_size" }
   ]
  },
  {
   "title": "Valid attestations per batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slasher_num_attestations_valid" }
   ]
  },
  {
   "title": "Deferred attestations per batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slasher_num_attestations_deferred"
    }
   ]
  },
  {
   "title": "Dropped attestations per batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slasher_num_attestations_dropped"
    }
   ]
  },
  {
   "title": "Blocks per batch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slasher_num_blocks_processed" }
   ]
  },
  {
   "title": "Chunk compression ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slasher_compression_ratio" }
   ]
  },
  {
   "title": "Chunks updated per batch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(slasher_num_chunks_updated[5m])"
    }
   ]
  }
 ]
}